### ISSUE TITLE
disable option for wrapper sidebar

### ISSUE THREAD

**Issue by achaayb** [omarKazoum/Application-de-gestion-d-cole#20]
@ admin panel. the base sidebar is shown with static base links wich are irrelevant in the admin panel
add disable option incase im using ajax
add config option to custom configure the sidebar

**Comment by omarKazoum** [comment]
you may now use viewNoSidebar($viewName,$viewParams); to show a view with only navbar (no sidebar).
also added Router::isRequestFor($label) to check if the current request corresponds to the label passed to Router::get() as a third param.
