### ISSUE TITLE
all crud data should be public.

### ISSUE THREAD

**Issue by achaayb** [omarKazoum/Application-de-gestion-d-cole#22]
Warning: Undefined property: models\Admin::$nom in C:\xampp\htdocs\Application-de-gestion-d-cole\views\adminCrud.php on line 271
Warning: Undefined property: models\Admin::$prenom in C:\xampp\htdocs\Application-de-gestion-d-cole\views\adminCrud.php on line 271

why would user data be protected/private?

**Comment by omarKazoum** [comment]
@achaayb models\Admin::$nom is a proprety in the class models\Admin that you should have defined so it's up to you to make it private or public or even static according to your imagination and your needs.

**Comment by omarKazoum** [comment]
as a reminder if a proprety is not decalred as static you may access it in this way $instance->somePropretyName
