### ISSUE TITLE
Parse entity static method should be dynamic.

### ISSUE THREAD

**Issue by achaayb** [omarKazoum/Application-de-gestion-d-cole#23]

**Comment by omarKazoum** [comment]
@achaayb please elaborate the issue with an example use case !

**Comment by achaayb** [comment]
`
<?php
$object = new StdClass;
$object->car1 = "porsche";
$object->car2 = "bugatti";

return (array) $object;
?>
instead of
<?php
$object = new StdClass;

return array('car1'=>$object->car1, 'car2'=>$object->car2);
?>
`

**Comment by omarKazoum** [comment]
great idea to use StdClass !
